apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    webhook-enabled: "true"
    environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    webhook-enabled: "true"
    environment: "staging"
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    webhook-enabled: "false"
    environment: "development"
