apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    jenkins: slave
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

 
