apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: workload-split
      maxSkew: 2
      topologyKey: capacity-spread
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchExpressions:
        - key: security
          operator: In
          values:
          - S2
      maxSkew: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule    
