{{- if .Values.certificate.useEmbeddedScript }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded  
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded  
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mutating-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mutating-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded  
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded  
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mutating-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mutating-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded  
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "mutating-webhook.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mutating-webhook.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: cert-generator
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "/scripts/generate-certs.sh"]
        volumeMounts:
        - name: cert-gen-script
          mountPath: /scripts
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: cert-gen-script
        configMap:
          name: {{ include "mutating-webhook.fullname" . }}-cert-script
          defaultMode: 0755
      - name: tmp
        emptyDir: {}

{{- end }}
