
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "mutating-webhook.fullname" .  }}-tls
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "mutating-webhook.gen-certs" . ) | indent 2 }}